USE [ESTUDOS_SQLSERVER]

GO
IF (OBJECT_ID(N'dbo.ESTADOS', N'U') IS NOT NULL)
BEGIN
	DROP TABLE dbo.PAIS;
END

-- Create table ESTADOS
CREATE TABLE ESTADOS (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL,
    UF VARCHAR(3) NOT NULL,
	DESCRIPTION VARCHAR(255) NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
    PAIS_ID_FK INT NOT NULL,
	CONSTRAINT fk_pais_estados 
	FOREIGN KEY (PAIS_ID_FK) 
	REFERENCES PAIS(ID)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
);
GO