USE [ESTUDOS_SQLSERVER]

GO
IF (OBJECT_ID(N'dbo.CIDADES', N'U') IS NOT NULL)
BEGIN
	DROP TABLE dbo.CIDADES;
END

CREATE TABLE CIDADES (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255) NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
  ESTADO_ID_FK INT NOT NULL,
	CONSTRAINT fk_estados_cidades
	FOREIGN KEY (ESTADO_ID_FK) 
	REFERENCES ESTADOS(ID)
	ON UPDATE CASCADE
	ON DELETE NO ACTION
);
GO