USE [ESTUDOS_SQLSERVER]

IF (OBJECT_ID(N'dbo.PAIS', N'U') IS NOT NULL)
BEGIN
	DROP TABLE dbo.PAIS;
END

CREATE TABLE PAIS (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(255) NULL,
	ACTIVE BIT NOT NULL DEFAULT 1, 
);